version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    user: "rails"
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/myapp:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
